### ISSUE TITLE
Redirect/navigate on wildcard, how?

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#53]
I have an internationalized application, paths are prefixed with the current language.
I would like to redirect the visitor using the data contained in the path, as you can see in this component [here](https://github.com/Coachonko/coachonko.com/blob/master/src/components/TranslatedNotFound.jsx).
How would I do that?
I think the information that most closely describes the Dark web-router API, that I can find, is [this one here](https://github.com/atellmer/dark/tree/master/packages/web-router#imperative-access-to-router), is this how?

**Comment by atellmer** [comment]
You need to use the `useHistory` hook

```tsx
const TranslatedNotFound = component(() => {
  const history = useHistory();

  useEffect(() => {
    if (notFound) {
      history.push('/new/route');
      // if don't need to save the current route in the browser history
      // history.replace('/new/route');
    }
  }, [somedep]);

  return null;
});
```

**Comment by Coachonko** [comment]
Thank you, this is good information.
Also I think I'm stupid. I should just wildcard `${lang}/**`

**Comment by atellmer** [comment]
In your case with lang you can use this approach - lang as parameter

```tsx
import { type DarkElement, h, Fragment, component, useEffect } from '@dark-engine/core';
import { createRoot } from '@dark-engine/platform-browser';
import { type Routes, Router, RouterLink, useHistory, useParams } from '@dark-engine/web-router';

const Shell = component<{ slot: DarkElement }>(({ slot }) => {
  const params = useParams();
  const history = useHistory();
  const lang = params.get('lang');

  useEffect(() => {
    if (lang !== 'en' && lang !== 'it') {
      history.replace('/en/home');
    }
  }, [lang]);

  return (
    <div>
      Shell {lang} {slot}
    </div>
  );
});

const Nav = component(() => {
  const params = useParams();
  const lang = params.get('lang');

  return (
    <nav>
      <RouterLink to={`/${lang}/home`}>Home</RouterLink>
      <RouterLink to={`/${lang}/contacts`}>Contacts</RouterLink>
      <RouterLink to={`/${lang}/about`}>About</RouterLink>
      <RouterLink to='/xxx'>404</RouterLink>
    </nav>
  );
});

const Home = component(() => {
  return <div>home</div>;
});

const Contacts = component(() => {
  return <div>Contacts</div>;
});

const About = component(() => {
  return <div>About</div>;
});

const routes: Routes = [
  {
    path: ':lang',
    component: Shell,
    children: [
      {
        path: 'home',
        component: Home,
      },
      {
        path: 'about',
        component: About,
      },
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: '',
        redirectTo: 'home',
      },
      {
        path: '**',
        redirectTo: 'home',
      },
    ],
  },
  {
    path: '',
    redirectTo: ':lang/home',
  },
  {
    path: '**',
    redirectTo: ':lang/home',
  },
];

const App = component(() => {
  return (
    <Router routes={routes}>
      {slot => (
        <main>
          <Nav />
          {slot}
        </main>
      )}
    </Router>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

Wilcard always will be just `**`, not `some/**`

I will publish the packages after small minor changes soon. (possibly tomorrow)

**Comment by Coachonko** [comment]
> In your case with lang you can use this approach - lang as parameter

I really don't remember why but I purposely avoided that with react router and inferno router before. I remember running into a messy problem. Since then I just iterate and register an independent route for each language instead. 
I may be crazy but I think it may be less computationally expensive to have a large routes array instead.
I will try this approach and see if I run into issues and remember what the issue was.

> Wilcard always will be just `**`, not `some/**`

Oh. Alright. Then useHistory is the solution for me

**Comment by atellmer** [comment]
> I will try this approach and see if I run into issues and remember what the issue was.

Ok. it will be intresting I think.

**Comment by Coachonko** [comment]
I am attempting what you suggested
```js
const baseRoutes = [
  {
    path: '/',
    pathMatch: 'full',
    component: lazy(() => import('../pages/Home'))
  },
  {
    path: 'contact',
    pathMatch: 'full',
    component: lazy(() => import('../pages/Contact'))
  },
  {
    path: 'not-found',
    pathMatch: 'full',
    component: lazy(() => import('../pages/NotFound'))
  },
  {
    path: '**',
    redirect: 'not-found'
  }
]

export const routes = [
  {
    path: '',
    component: lazy(() => import('../components/Root')),
    children: [...baseRoutes]
  },
  {
    path: ':lang',
    component: lazy(() => import('../components/Root')),
    children: [...baseRoutes]
  }
]
```
I am trying this, but I am experiencing something I don't understand.
navigating to `/de` for example, immediately redirects to `/`. I have no redirects anywhere, except for the wildcard routes.
```
root rendered
match:  {
  path: "/:lang/",
  url: "/de/",
}
params:  Map {}
home rerendered
```
It looks like `/de` matches the `:lang` route, but the params map is empty.

**Comment by atellmer** [comment]
Try this code (very similar), it works fine.

```tsx
import { type DarkElement, component, useEffect } from '@dark-engine/core';
import { createRoot } from '@dark-engine/platform-browser';
import { type Routes, Router, RouterLink, useHistory, useParams } from '@dark-engine/web-router';

const Root = component<{ slot: DarkElement }>(({ slot }) => {
  const params = useParams();
  const history = useHistory();
  const lang = params.get('lang');

  useEffect(() => {
    if (lang !== 'en' && lang !== 'it') {
      history.replace('/en');
    }
  }, [lang]);

  return (
    <div>
      Shell {lang} {slot}
    </div>
  );
});

const Nav = component(() => {
  const params = useParams();
  const lang = params.get('lang');

  console.log('params', params);

  return (
    <nav>
      <RouterLink to={`/${lang}`}>Home</RouterLink>
      <RouterLink to={`/${lang}/contacts`}>Contacts</RouterLink>
      <RouterLink to={`/${lang}/about`}>About</RouterLink>
      <RouterLink to='/xxx'>404</RouterLink>
    </nav>
  );
});

const Home = component(() => {
  return <div>home</div>;
});

const Contacts = component(() => {
  return <div>Contacts</div>;
});

const About = component(() => {
  return <div>About</div>;
});

const routes: Routes = [
  {
    path: ':lang',
    component: Root,
    children: [
      {
        path: '',
        component: Home,
      },
      {
        path: 'about',
        component: About,
      },
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: '**',
        redirectTo: '',
      },
    ],
  },
  {
    path: '',
    redirectTo: ':lang',
  },
  {
    path: '**',
    redirectTo: ':lang',
  },
];

const App = component(() => {
  return (
    <Router routes={routes}>
      {slot => (
        <main>
          <Nav />
          {slot}
        </main>
      )}
    </Router>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

Also you can remove the part with

```tsx
{
    path: '',
    component: lazy(() => import('../components/Root')),
    children: [...baseRoutes]
},
```

because `''` less specific than `:lang` and is found first.
When using parameters, it will not be possible to intercept the route via `**` and component, because anything can match the parameter.

Also I published 1.1.0 version of packages.

**Comment by Coachonko** [comment]
I see, I think I understand, but not fully.

The thing is I want default-language routes to have no language prefix. For example
`/` is default language
`/de` is alternate language (german)
`/contact` is default language
`/de/contact` is alternate language (german)
I was hoping that by placing `/` above, it would match the non-prefixed paths first and fallback to prefixed paths after.

**Comment by atellmer** [comment]
Then that changes things. In this case, the parameters will not help. Only a static description of routes will help, as you did earlier.

**Comment by atellmer** [comment]
We need to support something like this

```tsx
const routes: Routes = [
  {
    path: 'de',
    component: Root,
    children: [
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: '**',
        pathMatch: 'full',
        redirectTo: '/not-found',
      },
    ],
  },
  {
    path: '',
    component: Root,
    children: [
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: 'not-found',
        component: NotFound,
      },
    ],
  },
  {
    path: '**',
    redirectTo: 'not-found',
  },
];
```

**Comment by Coachonko** [comment]
Now I wonder how other routers handle this.
If you decide to support some sort of i18n routing on web-router I think it should be able to handle any number of alternate languages.
I have upgraded to 1.1.0 and fixed up the routing in my repository. I think I made it work fine by generating a large array, one route object for each route and no children.

**Comment by atellmer** [comment]
> I think it should be able to handle any number of alternate languages, not just one.

Yea, I mean

```tsx
const routes: Routes = [
  ...['en', 'it', 'fr'].map(lang => ({
    path: lang,
    component: Root,
    children: [
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: '**',
        pathMatch: 'full',
        redirectTo: '/not-found',
      },
    ],
  })),
  {
    path: '',
    component: Root,
    children: [
      {
        path: 'contacts',
        component: Contacts,
      },
      {
        path: 'not-found',
        component: NotFound,
      },
    ],
  },
  {
    path: '**',
    redirectTo: 'not-found',
  },
];
```

Hope it won't be difficult.

**Comment by Coachonko** [comment]
I was investigating how other routers work in other frameworks, the following works in React Router
```js
const routes = [
  {
    path: '/',
    element: <Root />,
    children: [
      {
        path: '', // matches /
        element: <Home />
      },
      {
        path: 'contact', //matches /contact
        element: <Contact />
      },
      {
        path: 'de',
        children: [
          {
            path: '', // matches /de
            element: <Home />
          },
          {
            path: 'contact', // matches /de/contact
            element: <Contact />
          }
        ]
      }
    ]
  }
]
```
Just noting it here.

**Comment by atellmer** [comment]
Thanks for your investigation. With some fixes in open PR it will work pretty much the same way.

```tsx
const routes = [
  {
    path: '/',
    component: Root,
    children: [
      {
        path: '/', // matches /
        component: Home,
      },
      {
        path: 'contact', //matches /contact
        component: Contacts,
      },
      {
        path: 'de',
        component: component(({ slot }) => slot), // should be here
        children: [
          {
            path: '/', // matches /de
            component: Home,
          },
          {
            path: 'contact', // matches /de/contact
            component: Contacts,
          },
        ],
      },
    ],
  },
  {
    path: '**',
    redirectTo: '/',
  },
];
```

**Comment by Coachonko** [comment]
Awesome, the fix you pushed works great. Thank you, this greatly simplifies my app.

I have a question: 
```js
export const baseRoutes = [
  {
    path: '/',
    component: lazy(() => import('../pages/Home')),
    seo: 'home'
  },
  {
    path: '/contact',
    component: lazy(() => import('../pages/Contact')),
    seo: 'contact'
  },
  {
    path: '/not-found',
    component: lazy(() => import('../pages/NotFound'))
  }
]


function generateRoutes (baseRoutes) {
  const alternateLanguageRoutes = []
  for (let i = 1, len = languages.length; i < len; i++) { // skip default language
    const language = languages[i]
    alternateLanguageRoutes.push({
      path: `/${language}`,
      component: Root,
      children: [
        ...baseRoutes,
        {
          path: '**',
          redirectTo: '/not-found'
        }
      ]
    })
  }
  return [
    {
      path: '/',
      component: Root,
      children: [
        ...baseRoutes,
        ...alternateLanguageRoutes,
        {
          path: '**',
          redirectTo: '/not-found'
        }
      ]
    }
  ]
}

export const routes = generateRoutes(baseRoutes)
```
The above works, however if I add `pathMatch: full` to `/contact`, the app redirects `/de/contact` to `/de`.
And if I add `pathMatch: full` to `/not-found`, then the app breaks when requesting `/de/contact`.
Any clue why?

The JSON.strigify(routes) output is as follows.
```js
[
  {
    "path": "/",
    "children": [
      {
        "path": "/",
        "seo": "home"
      },
      {
        "path": "/contact",
        "pathMatch": "full",
        "seo": "contact"
      },
      {
        "path": "/not-found",
        "pathMatch": "full"
      },
      {
        "path": "/de",
        "children": [
          {
            "path": "/",
            "seo": "home"
          },
          {
            "path": "/contact",
            "pathMatch": "full",
            "seo": "contact"
          },
          {
            "path": "/not-found",
            "pathMatch": "full"
          },
          {
            "path": "**",
            "redirectTo": "/not-found"
          }
        ]
      },
      {
        "path": "**",
        "redirectTo": "/not-found"
      }
    ]
  }
]
```

**Comment by atellmer** [comment]
Routing breaks because you use `pathMatch: 'full'` incorrectly. `full` means that you must always write the path from start. In most cases it useful if you want make a redirect from child route to any parent or sibling route. In the code above no need using `full` option.

Your worked example
![1](https://github.com/atellmer/dark/assets/16635118/0536856a-9e4e-4022-b35c-f037e20f7bd8)

**Comment by Coachonko** [comment]
> Routing breaks because you use `pathMatch: 'full'` incorrectly. `full` means that you must always write the path from start. In most cases it useful if you want make a redirect from child route to any parent or sibling route (into another place of routes tree). In the code above no need using `full` option.

Oh I understand! So the route must be defined with the full path to match the path fully. Thank you.

**Comment by atellmer** [comment]
I have trouble with your bun server. Any ideas?

```
npm start

> start
> bun run ./server/index.js

18 |   }
19 | }
20 |
21 | async function generateSitemapIndex (paths) {
22 |   const indexPath = `${process.cwd()}${paths.index}`
23 |   const file = Bun.file(indexPath)
                    ^
TypeError: Failed to create FileSink: src.windows_c.E.NOENT
 code: "ERR_INVALID_ARG_TYPE"

      at D:\apps\coachonko.com\server\sitemaps.js:23:16
      at generateSitemapIndex (D:\apps\coachonko.com\server\sitemaps.js:21:38)
      at D:\apps\coachonko.com\server\sitemaps.js:14:11
      at generateSitemaps (D:\apps\coachonko.com\server\sitemaps.js:7:40)
      at D:\apps\coachonko.com\server\index.js:7:7
```

**Comment by Coachonko** [comment]
Are you on windows? I am on linux so I can't reproduce

**Comment by atellmer** [comment]
Yes, win 11. Anyway server started. And I see broken html there
![1](https://github.com/atellmer/dark/assets/16635118/09e504d8-c003-422a-8f38-59401d4eb2a3)

It seems I will long debug tomorrow

**Comment by atellmer** [comment]
The problem in `platform-server` I think. It breaks on `<br />` and returns inconsistent html without `<br>` tag and we have hydration error under the hood.

Yea, we need think about better algorithm for match active links.

**Comment by Coachonko** [comment]
Thank you for taking a look at the issues

**Comment by atellmer** [comment]
version 1.2.0 is available
